import Foundation
import Testing
@testable import Termura

// MARK: - Test Helpers

private func makeTempDir() throws -> String {
    let tmp = NSTemporaryDirectory() + "termura-injection-test-\(UUID().uuidString)"
    try FileManager.default.createDirectory(
        atPath: tmp,
        withIntermediateDirectories: true
    )
    return tmp
}

private func makeHandoffService() -> SessionHandoffService {
    SessionHandoffService(
        messageRepo: MockSessionMessageRepository(),
        harnessEventRepo: MockHarnessEventRepository(),
        summarizer: BranchSummarizer()
    )
}

private func makeInjectionService() -> ContextInjectionService {
    ContextInjectionService(handoffService: makeHandoffService())
}

private func writeContextFile(
    projectRoot: String,
    agentType: String = "claudeCode",
    taskStatus: String = "Implementing feature X"
) throws {
    let dirPath = (projectRoot as NSString)
        .appendingPathComponent(AppConfig.SessionHandoff.directoryName)
    try FileManager.default.createDirectory(
        atPath: dirPath,
        withIntermediateDirectories: true
    )
    let filePath = (dirPath as NSString)
        .appendingPathComponent(AppConfig.SessionHandoff.contextFileName)
    let content = """
    # Session Context (Auto-generated by Termura)

    > Last updated: 2026-03-23 10:00 | Agent: \(agentType) | Duration: 5min

    ## Current Task Status

    \(taskStatus)

    ## Recent Decisions

    - **2026-03-23 09:55**: Chose approach A because it was simpler

    ## Key Errors Encountered

    - `error: type mismatch`
    """
    try content.write(toFile: filePath, atomically: true, encoding: .utf8)
}

// MARK: - Tests

@Suite("ContextInjectionService")
struct ContextInjectionServiceTests {

    @Test("Returns nil when no context.md exists")
    func noContextFile() async throws {
        let tmpDir = try makeTempDir()
        defer { try? FileManager.default.removeItem(atPath: tmpDir) }

        let service = makeInjectionService()
        let result = await service.buildInjectionText(projectRoot: tmpDir)
        #expect(result == nil)
    }

    @Test("Returns injection text for Claude Code agent")
    func claudeCodeInjection() async throws {
        let tmpDir = try makeTempDir()
        defer { try? FileManager.default.removeItem(atPath: tmpDir) }

        try writeContextFile(projectRoot: tmpDir, agentType: "claudeCode")

        let service = makeInjectionService()
        let result = await service.buildInjectionText(projectRoot: tmpDir)

        #expect(result != nil)
        let text = try #require(result)
        #expect(text.contains("claude --continue"))
    }

    @Test("Returns injection text for Aider agent")
    func aiderInjection() async throws {
        let tmpDir = try makeTempDir()
        defer { try? FileManager.default.removeItem(atPath: tmpDir) }

        try writeContextFile(projectRoot: tmpDir, agentType: "aider")

        let service = makeInjectionService()
        let result = await service.buildInjectionText(projectRoot: tmpDir)

        #expect(result != nil)
    }

    @Test("Returns printf command for unknown agent")
    func shellInjection() async throws {
        let tmpDir = try makeTempDir()
        defer { try? FileManager.default.removeItem(atPath: tmpDir) }

        try writeContextFile(projectRoot: tmpDir, agentType: "unknown")

        let service = makeInjectionService()
        let result = await service.buildInjectionText(projectRoot: tmpDir)

        #expect(result != nil)
        let text = try #require(result)
        #expect(text.contains("printf"))
    }

    @Test("Shell format uses printf with single-quoted argument")
    func shellFormatUsesPrintf() async throws {
        let tmpDir = try makeTempDir()
        defer { try? FileManager.default.removeItem(atPath: tmpDir) }

        try writeContextFile(projectRoot: tmpDir, agentType: "unknown")

        let service = makeInjectionService()
        let text = try #require(await service.buildInjectionText(projectRoot: tmpDir))
        #expect(text.hasPrefix("printf '%s\\n' '"))
    }

    @Test("Shell format escapes single quotes in task status")
    func shellEscapesSingleQuotes() async throws {
        let tmpDir = try makeTempDir()
        defer { try? FileManager.default.removeItem(atPath: tmpDir) }

        try writeContextFile(projectRoot: tmpDir, agentType: "unknown", taskStatus: "it's a test")

        let service = makeInjectionService()
        let text = try #require(await service.buildInjectionText(projectRoot: tmpDir))
        // Single quotes inside the value are escaped as '\''
        #expect(text.contains("'\\''"))
    }

    @Test("Shell format includes decision summaries")
    func shellFormatIncludesDecisions() async throws {
        let tmpDir = try makeTempDir()
        defer { try? FileManager.default.removeItem(atPath: tmpDir) }

        try writeContextFile(projectRoot: tmpDir, agentType: "unknown")

        let service = makeInjectionService()
        let text = try #require(await service.buildInjectionText(projectRoot: tmpDir))
        #expect(text.contains("Decisions:"))
    }

    @Test("Injection text is truncated to injectionMaxLength")
    func truncation() async throws {
        let tmpDir = try makeTempDir()
        defer { try? FileManager.default.removeItem(atPath: tmpDir) }

        let longTask = String(repeating: "A long task description. ", count: 200)
        try writeContextFile(projectRoot: tmpDir, taskStatus: longTask)

        let service = makeInjectionService()
        let result = await service.buildInjectionText(projectRoot: tmpDir)

        #expect(result != nil)
        let text = try #require(result)
        #expect(text.count <= AppConfig.SessionHandoff.injectionMaxLength)
    }

    @Test("Empty project root returns nil")
    func emptyProjectRoot() async throws {
        let service = makeInjectionService()
        let result = await service.buildInjectionText(projectRoot: "")
        #expect(result == nil)
    }
}
