import Foundation
import Testing
@testable import Termura

@Suite("SessionHandoffService Markdown")
struct SessionHandoffServiceMarkdownTests {
    /// The service needs real repos but we only test Markdown methods,
    /// so create a lightweight instance with mock repos.
    private func makeService() async throws -> SessionHandoffService {
        let msgRepo = MockSessionRepository.InlineMessageRepo()
        let eventRepo = MockHarnessEventRepo()
        return SessionHandoffService(
            messageRepo: msgRepo,
            harnessEventRepo: eventRepo,
            summarizer: BranchSummarizer()
        )
    }

    private func makeContext(
        taskStatus: String = "Implementing feature X",
        decisions: [DecisionEntry] = [],
        errors: [String] = [],
        agentType: AgentType? = .claudeCode,
        duration: TimeInterval = 600,
        date: Date = Date(timeIntervalSince1970: 1_700_000_000)
    ) -> HandoffContext {
        HandoffContext(
            taskStatus: taskStatus,
            decisions: decisions,
            errors: errors,
            agentType: agentType,
            sessionDuration: duration,
            lastUpdated: date
        )
    }

    // MARK: - Render

    @Test("Render contains header with agent and duration")
    func renderHeader() async throws {
        let service = try await makeService()
        let ctx = makeContext(agentType: .claudeCode, duration: 600)
        let md = await service.renderContextMarkdown(ctx)
        #expect(md.contains("Agent: claudeCode"))
        #expect(md.contains("10min"))
    }

    @Test("Render contains task status section")
    func renderTaskStatus() async throws {
        let service = try await makeService()
        let ctx = makeContext(taskStatus: "Working on auth")
        let md = await service.renderContextMarkdown(ctx)
        #expect(md.contains("## Current Task Status"))
        #expect(md.contains("Working on auth"))
    }

    @Test("Render includes decisions section when non-empty")
    func renderDecisions() async throws {
        let service = try await makeService()
        let ctx = makeContext(decisions: [
            DecisionEntry(timestamp: Date(timeIntervalSince1970: 1_700_000_000), summary: "Use async/await")
        ])
        let md = await service.renderContextMarkdown(ctx)
        #expect(md.contains("## Recent Decisions"))
        #expect(md.contains("Use async/await"))
    }

    @Test("Render omits decisions section when empty")
    func renderNoDecisions() async throws {
        let service = try await makeService()
        let ctx = makeContext(decisions: [])
        let md = await service.renderContextMarkdown(ctx)
        #expect(!md.contains("## Recent Decisions"))
    }

    @Test("Render includes errors section when non-empty")
    func renderErrors() async throws {
        let service = try await makeService()
        let ctx = makeContext(errors: ["module not found"])
        let md = await service.renderContextMarkdown(ctx)
        #expect(md.contains("## Key Errors"))
        #expect(md.contains("`module not found`"))
    }

    @Test("Render omits errors section when empty")
    func renderNoErrors() async throws {
        let service = try await makeService()
        let ctx = makeContext(errors: [])
        let md = await service.renderContextMarkdown(ctx)
        #expect(!md.contains("## Key Errors"))
    }

    @Test("Short duration shows <1min")
    func renderShortDuration() async throws {
        let service = try await makeService()
        let ctx = makeContext(duration: 30)
        let md = await service.renderContextMarkdown(ctx)
        #expect(md.contains("<1min"))
    }

    // MARK: - Parse

    @Test("Parse extracts task status")
    func parseTaskStatus() async throws {
        let service = try await makeService()
        let md = """
        # Session Context (Auto-generated by Termura)

        > Last updated: 2023-11-14 22:13 | Agent: claudeCode | Duration: 10min

        ## Current Task Status

        Implementing feature X
        """
        let ctx = await service.parseContextMarkdown(md)
        #expect(ctx != nil)
        #expect(ctx?.taskStatus == "Implementing feature X")
    }

    @Test("Parse extracts agent type")
    func parseAgentType() async throws {
        let service = try await makeService()
        let md = """
        # Session Context (Auto-generated by Termura)

        > Last updated: 2023-11-14 22:13 | Agent: aider | Duration: 5min

        ## Current Task Status

        Working
        """
        let ctx = await service.parseContextMarkdown(md)
        #expect(ctx?.agentType == .aider)
    }

    @Test("Parse extracts decisions")
    func parseDecisions() async throws {
        let service = try await makeService()
        let md = """
        # Session Context (Auto-generated by Termura)

        > Last updated: 2023-11-14 22:13 | Agent: claudeCode | Duration: 10min

        ## Current Task Status

        Working on tests

        ## Recent Decisions

        - **2023-11-14 22:00**: Use async/await
        - **2023-11-14 22:10**: Add error handling
        """
        let ctx = await service.parseContextMarkdown(md)
        #expect(ctx?.decisions.count == 2)
        #expect(ctx?.decisions.first?.summary == "Use async/await")
    }

    @Test("Parse returns nil for empty content")
    func parseEmptyContent() async throws {
        let service = try await makeService()
        let ctx = await service.parseContextMarkdown("just random text")
        #expect(ctx == nil)
    }

    @Test("Render then parse round-trips task status")
    func roundTrip() async throws {
        let service = try await makeService()
        let original = makeContext(taskStatus: "Round trip test")
        let md = await service.renderContextMarkdown(original)
        let parsed = await service.parseContextMarkdown(md)
        #expect(parsed?.taskStatus == "Round trip test")
    }
}

// MARK: - Inline mocks for SessionHandoffService construction

private extension MockSessionRepository {
    actor InlineMessageRepo: SessionMessageRepositoryProtocol {
        func fetchMessages(for _: SessionID, contentType _: MessageContentType?) async throws -> [SessionMessage] { [] }
        func save(_: SessionMessage) async throws {}
        func delete(id _: SessionMessageID) async throws {}
        func deleteAll(for _: SessionID) async throws {}
        func countTokens(for _: SessionID, contentType _: MessageContentType) async throws -> Int { 0 }
    }
}

private actor MockHarnessEventRepo: HarnessEventRepositoryProtocol {
    func fetchEvents(for _: SessionID) async throws -> [HarnessEvent] { [] }
    func save(_: HarnessEvent) async throws {}
    func fetchEvents(ofType _: HarnessEventType, for _: SessionID) async throws -> [HarnessEvent] { [] }
}
