import Foundation

/// Renders a session + output chunks as a self-contained HTML document.
/// All user-provided content is HTML-escaped to prevent XSS.
enum HTMLRenderer {
    static func render(session: SessionRecord, chunks: [OutputChunk]) -> String {
        let title = escapeHTML(session.title)
        let date = ISO8601DateFormatter().string(from: session.createdAt)
        let branchInfo = session.branchType != .main
            ? " <span class=\"badge\">\(escapeHTML(session.branchType.rawValue))</span>"
            : ""

        var html = """
        <!DOCTYPE html>
        <html lang="en">
        <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>\(title) — Termura Export</title>
        <style>\(css)</style>
        </head>
        <body>
        <header>
        <h1>\(title)\(branchInfo)</h1>
        <p class="meta">Exported from Termura · \(date)
         · \(escapeHTML(session.workingDirectory))</p>
        </header>
        <main>
        """

        let limited = chunks.prefix(AppConfig.Export.maxExportMessages)
        for chunk in limited {
            html += renderChunk(chunk)
        }

        html += """
        </main>
        <footer>
        <p>Generated by <strong>Termura</strong></p>
        </footer>
        </body>
        </html>
        """
        return html
    }

    // MARK: - Chunk rendering

    private static func renderChunk(_ chunk: OutputChunk) -> String {
        let exitBadge: String
        if let code = chunk.exitCode {
            let cls = code == 0 ? "exit-ok" : "exit-fail"
            exitBadge = " <span class=\"\(cls)\">exit \(code)</span>"
        } else {
            exitBadge = ""
        }

        let command = escapeHTML(chunk.commandText)
        let typeClass = chunk.contentType.rawValue
        let body = chunk.outputLines
            .map { escapeHTML($0) }
            .joined(separator: "\n")

        return """
        <details class="chunk \(typeClass)" open>
        <summary>\(command)\(exitBadge)</summary>
        <pre><code>\(body)</code></pre>
        </details>
        """
    }

    // MARK: - Security

    static func escapeHTML(_ string: String) -> String {
        string
            .replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
            .replacingOccurrences(of: "'", with: "&#39;")
    }

    // MARK: - Embedded CSS

    private static let css = """
    :root {
      --bg: #1e1e2e; --fg: #cdd6f4; --accent: #89b4fa;
      --ok: #a6e3a1; --fail: #f38ba8; --border: #313244;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "SF Mono", monospace;
      background: var(--bg); color: var(--fg);
      max-width: 900px; margin: 0 auto; padding: 24px;
    }
    header { margin-bottom: 24px; border-bottom: 1px solid var(--border); padding-bottom: 16px; }
    h1 { font-size: 1.4em; }
    .meta { font-size: 0.85em; opacity: 0.6; margin-top: 4px; }
    .badge {
      background: var(--accent); color: var(--bg);
      padding: 2px 8px; border-radius: 4px; font-size: 0.75em;
    }
    .chunk { margin-bottom: 12px; border: 1px solid var(--border); border-radius: 6px; }
    .chunk summary {
      cursor: pointer; padding: 8px 12px; font-weight: 600;
      background: rgba(255,255,255,0.03); border-radius: 6px 6px 0 0;
    }
    .chunk pre { padding: 12px; overflow-x: auto; font-size: 0.9em; }
    .exit-ok { color: var(--ok); font-size: 0.8em; margin-left: 8px; }
    .exit-fail { color: var(--fail); font-size: 0.8em; margin-left: 8px; }
    footer { margin-top: 32px; font-size: 0.8em; opacity: 0.4; text-align: center; }
    """
}
