import Foundation

extension SessionHandoffService {
    // MARK: - Markdown Rendering

    func renderContextMarkdown(_ context: HandoffContext) -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd HH:mm"
        let dateStr = formatter.string(from: context.lastUpdated)

        let agentName = context.agentType.map(\.rawValue) ?? "Unknown"
        let durationMin = Int(context.sessionDuration / 60)
        let durationStr = durationMin > 0 ? "\(durationMin)min" : "<1min"

        var lines: [String] = []
        lines.append("# Session Context (Auto-generated by Termura)")
        lines.append("")
        lines.append("> Last updated: \(dateStr) | Agent: \(agentName) | Duration: \(durationStr)")
        lines.append("")
        lines.append("## Current Task Status")
        lines.append("")
        lines.append(context.taskStatus)
        lines.append("")

        if !context.decisions.isEmpty {
            lines.append("## Recent Decisions")
            lines.append("")
            for entry in context.decisions {
                let timestamp = formatter.string(from: entry.timestamp)
                lines.append("- **\(timestamp)**: \(entry.summary)")
            }
            lines.append("")
        }

        if !context.errors.isEmpty {
            lines.append("## Key Errors Encountered")
            lines.append("")
            for error in context.errors {
                lines.append("- `\(error)`")
            }
            lines.append("")
        }

        return lines.joined(separator: "\n")
    }

    // MARK: - Parsing

    func parseContextMarkdown(_ content: String) -> HandoffContext? {
        let lines = content.components(separatedBy: "\n")
        var taskStatus = ""
        var decisions: [DecisionEntry] = []
        var currentSection = ""
        var agentType: AgentType?

        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd HH:mm"

        for line in lines {
            if line.hasPrefix("> Last updated:"), agentType == nil {
                agentType = parseAgentTypeFromHeader(line)
            }
            if line.hasPrefix("## Current Task Status") {
                currentSection = "task"
                continue
            } else if line.hasPrefix("## Recent Decisions") {
                currentSection = "decisions"
                continue
            } else if line.hasPrefix("## ") {
                currentSection = "other"
                continue
            }

            switch currentSection {
            case "task":
                let trimmed = line.trimmingCharacters(in: .whitespacesAndNewlines)
                if !trimmed.isEmpty {
                    if !taskStatus.isEmpty { taskStatus += "\n" }
                    taskStatus += trimmed
                }
            case "decisions":
                if let entry = parseDecisionLine(line, formatter: formatter) {
                    decisions.append(entry)
                }
            default: break
            }
        }

        guard !taskStatus.isEmpty || !decisions.isEmpty else { return nil }
        return HandoffContext(
            taskStatus: taskStatus,
            decisions: decisions,
            errors: [],
            agentType: agentType,
            sessionDuration: 0,
            lastUpdated: Date()
        )
    }

    private func parseAgentTypeFromHeader(_ line: String) -> AgentType? {
        guard let agentRange = line.range(of: "Agent: ") else { return nil }
        let afterAgent = line[agentRange.upperBound...]
        let name = if let pipeRange = afterAgent.range(of: " |") {
            String(afterAgent[..<pipeRange.lowerBound])
        } else {
            String(afterAgent).trimmingCharacters(in: .whitespacesAndNewlines)
        }
        return AgentType(rawValue: name)
    }

    private func parseDecisionLine(_ line: String, formatter: DateFormatter) -> DecisionEntry? {
        guard line.hasPrefix("- **") else { return nil }
        let stripped = String(line.dropFirst(4))
        guard let endBold = stripped.range(of: "**:") else { return nil }
        let dateStr = String(stripped[stripped.startIndex ..< endBold.lowerBound])
        let summaryStart = stripped.index(endBold.upperBound, offsetBy: 0)
        let summary = String(stripped[summaryStart...]).trimmingCharacters(in: .whitespaces)
        guard let date = formatter.date(from: dateStr) else { return nil }
        return DecisionEntry(timestamp: date, summary: summary)
    }
}
