#!/usr/bin/env bash
# check-baseline-drift.sh
#
# Locks in the current open-core baseline:
#
#   1. `scripts/pre-commit` declares LEAK_PATTERN exactly once and the
#      value MUST be `termura-harness` (path-only). Any change to the
#      pattern body is rejected.
#   2. `scripts/pre-commit` declares SELF_EXCLUDE_FILES exactly once
#      with exactly four path tokens (`scripts/pre-commit`,
#      `scripts/regen-all.sh`, `scripts/quality-gate.sh`,
#      `scripts/check-baseline-drift.sh`). Adding a 5th entry is rejected.
#   3. `scripts/pre-commit` does NOT contain a `WHITELIST_REGEX` variable
#      anymore — re-introducing it is rejected.
#
# This script is itself self-excluded from the leak scanner because it
# prints the literals it checks for. CI runs this on every PR.
#
# Exit codes:
#   0 = clean (baseline intact)
#   1 = drift (failure with diagnostic message)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HOOK="$REPO_ROOT/scripts/pre-commit"

if [[ "${1:-}" == "--print" ]]; then
    if [[ ! -f "$HOOK" ]]; then
        echo "FAIL: $HOOK missing — cannot print open-core baseline." >&2
        exit 1
    fi
    cat <<'EOF'
## Open-core baseline (auto-generated by `scripts/check-baseline-drift.sh --print`)

The three invariants below are enforced by `scripts/check-baseline-drift.sh`,
which CI runs on every PR. CLAUDE.md §12.3 explains the rationale; this
section is the live reflection of what's actually locked.

### 1. LEAK_PATTERN (path-only, no type names)

EOF
    grep -E '^LEAK_PATTERN=' "$HOOK" | sed 's/^/    /'
    cat <<'EOF'

### 2. SELF_EXCLUDE_FILES (exactly four scanner / orchestrator scripts)

EOF
    grep -E '^SELF_EXCLUDE_FILES=' "$HOOK" | sed 's/^/    /'
    cat <<'EOF'

### 3. WHITELIST_REGEX (must remain deleted)

EOF
    if grep -qE '^WHITELIST_REGEX=' "$HOOK"; then
        echo "    DRIFT: WHITELIST_REGEX is currently present (regression)."
    else
        echo "    (absent, as required)"
    fi
    exit 0
fi

if [[ ! -f "$HOOK" ]]; then
    echo "FAIL: $HOOK missing — cannot verify open-core baseline." >&2
    exit 1
fi

# 1. LEAK_PATTERN must be the path-only literal.
LEAK_LINE_COUNT="$(grep -cE '^LEAK_PATTERN=' "$HOOK" || true)"
if [[ "$LEAK_LINE_COUNT" != "1" ]]; then
    echo "FAIL: scripts/pre-commit must declare LEAK_PATTERN exactly once (got $LEAK_LINE_COUNT)." >&2
    exit 1
fi
EXPECTED_LEAK_LINE="LEAK_PATTERN='termura-harness'"
if ! grep -qFx "$EXPECTED_LEAK_LINE" "$HOOK"; then
    echo "FAIL: scripts/pre-commit LEAK_PATTERN drifted from path-only baseline." >&2
    echo "       Expected: $EXPECTED_LEAK_LINE" >&2
    echo "       Got:      $(grep -E '^LEAK_PATTERN=' "$HOOK")" >&2
    echo "" >&2
    echo "Per CLAUDE.md §12.3, LEAK_PATTERN is path-only by design. Adding" >&2
    echo "type names defeats both review (rename bypass) and stub commits" >&2
    echo "(legitimate edits would fail). Reject this PR." >&2
    exit 1
fi

# 2. SELF_EXCLUDE_FILES must list exactly the three orchestrator scripts.
SELF_LINE_COUNT="$(grep -cE '^SELF_EXCLUDE_FILES=' "$HOOK" || true)"
if [[ "$SELF_LINE_COUNT" != "1" ]]; then
    echo "FAIL: scripts/pre-commit must declare SELF_EXCLUDE_FILES exactly once (got $SELF_LINE_COUNT)." >&2
    exit 1
fi
EXPECTED_SELF_LINE="SELF_EXCLUDE_FILES='^(scripts/pre-commit|scripts/regen-all\\.sh|scripts/quality-gate\\.sh|scripts/check-baseline-drift\\.sh)\$'"
if ! grep -qFx "$EXPECTED_SELF_LINE" "$HOOK"; then
    echo "FAIL: scripts/pre-commit SELF_EXCLUDE_FILES drifted from baseline." >&2
    echo "       Expected: $EXPECTED_SELF_LINE" >&2
    echo "       Got:      $(grep -E '^SELF_EXCLUDE_FILES=' "$HOOK")" >&2
    echo "" >&2
    echo "Per CLAUDE.md §12.3, SELF_EXCLUDE_FILES is reserved for the four" >&2
    echo "scanner / cross-repo orchestrator scripts that physically must" >&2
    echo "self-reference the leak literal. Adding any 5th entry is a" >&2
    echo "policy regression. Reject this PR." >&2
    exit 1
fi

# 3. WHITELIST_REGEX must remain deleted. Any reintroduction is rejected.
if grep -qE '^WHITELIST_REGEX=' "$HOOK"; then
    echo "FAIL: scripts/pre-commit reintroduced WHITELIST_REGEX." >&2
    echo "" >&2
    echo "Per CLAUDE.md §12.3, file-level whitelisting was deleted. Any" >&2
    echo "leak detected in a tracked file MUST be fixed by rewriting the" >&2
    echo "file or moving it to the private repo — never by re-adding it" >&2
    echo "to a whitelist. Reject this PR." >&2
    exit 1
fi

echo "OK: open-core baseline intact (LEAK_PATTERN + SELF_EXCLUDE_FILES + no WHITELIST_REGEX)."
exit 0
