#!/usr/bin/env bash
# Mirrors the version values you edited in Xcode UI (General -> Identity ->
# Version / Build) from Termura.xcodeproj/project.pbxproj into project.yml.
#
# Why this script exists:
# - .xcodeproj/ is gitignored and regenerated by `xcodegen generate`, so
#   Xcode UI edits in pbxproj would be lost on the next regen.
# - Mirroring into project.yml (git-tracked) makes Xcode UI the source of
#   truth while keeping xcodegen idempotent.
#
# Workflow:
#   1. Edit Version / Build in Xcode UI.
#   2. Run this script (or `make sync-version`).
#   3. Commit the project.yml change.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

PBXPROJ="Termura.xcodeproj/project.pbxproj"
PROJECT_YML="project.yml"

if [[ ! -f "$PBXPROJ" ]]; then
    echo "ERROR: $PBXPROJ not found. Run \`xcodegen generate\` first." >&2
    exit 1
fi

extract_unique() {
    local key="$1"
    grep -oE "${key} = [^;]+;" "$PBXPROJ" \
        | sed -E "s/${key} = (.+);/\\1/" \
        | sed -E 's/^"(.*)"$/\1/' \
        | sort -u
}

MARKETING_VALUES="$(extract_unique MARKETING_VERSION)"
PROJECT_VALUES="$(extract_unique CURRENT_PROJECT_VERSION)"

if [[ -z "$MARKETING_VALUES" ]]; then
    echo "ERROR: MARKETING_VERSION not found in $PBXPROJ." >&2
    echo "  Open Xcode and set a version in General -> Identity -> Version." >&2
    exit 1
fi

if [[ -z "$PROJECT_VALUES" ]]; then
    echo "ERROR: CURRENT_PROJECT_VERSION not found in $PBXPROJ." >&2
    echo "  Open Xcode and set a build number in General -> Identity -> Build." >&2
    exit 1
fi

if [[ "$(echo "$MARKETING_VALUES" | wc -l | tr -d ' ')" -ne 1 ]]; then
    echo "ERROR: Multiple distinct MARKETING_VERSION values in $PBXPROJ:" >&2
    echo "$MARKETING_VALUES" | sed 's/^/  /' >&2
    echo "  Set the same value across all configurations in Xcode." >&2
    exit 1
fi

if [[ "$(echo "$PROJECT_VALUES" | wc -l | tr -d ' ')" -ne 1 ]]; then
    echo "ERROR: Multiple distinct CURRENT_PROJECT_VERSION values in $PBXPROJ:" >&2
    echo "$PROJECT_VALUES" | sed 's/^/  /' >&2
    exit 1
fi

MV="$MARKETING_VALUES"
PV="$PROJECT_VALUES"

if ! grep -qE '^[[:space:]]+MARKETING_VERSION:' "$PROJECT_YML"; then
    echo "ERROR: project.yml has no MARKETING_VERSION line under settings.base." >&2
    echo "  Add it once manually, then re-run this script." >&2
    exit 1
fi

if ! grep -qE '^[[:space:]]+CURRENT_PROJECT_VERSION:' "$PROJECT_YML"; then
    echo "ERROR: project.yml has no CURRENT_PROJECT_VERSION line under settings.base." >&2
    exit 1
fi

# Capture pre-image so we can report a no-op cleanly.
OLD_MV="$(grep -E '^[[:space:]]+MARKETING_VERSION:' "$PROJECT_YML" | head -1 | sed -E 's/.*MARKETING_VERSION:[[:space:]]*"?([^"]*)"?[[:space:]]*$/\1/')"
OLD_PV="$(grep -E '^[[:space:]]+CURRENT_PROJECT_VERSION:' "$PROJECT_YML" | head -1 | sed -E 's/.*CURRENT_PROJECT_VERSION:[[:space:]]*"?([^"]*)"?[[:space:]]*$/\1/')"

# BSD sed (macOS) requires an explicit empty backup suffix.
sed -i '' -E "s|^([[:space:]]+MARKETING_VERSION:).*|\\1 \"${MV}\"|" "$PROJECT_YML"
sed -i '' -E "s|^([[:space:]]+CURRENT_PROJECT_VERSION:).*|\\1 \"${PV}\"|" "$PROJECT_YML"

if [[ "$OLD_MV" == "$MV" && "$OLD_PV" == "$PV" ]]; then
    echo "OK: project.yml already in sync (MARKETING_VERSION=${MV}, CURRENT_PROJECT_VERSION=${PV})."
else
    echo "OK: project.yml updated."
    echo "  MARKETING_VERSION:        ${OLD_MV} -> ${MV}"
    echo "  CURRENT_PROJECT_VERSION:  ${OLD_PV} -> ${PV}"
    echo "  Commit project.yml to persist the change."
fi
