#!/usr/bin/env bash
# Mirrors Xcode UI version edits (General → Identity → Version / Build) from
# every pbxproj this codebase generates into the corresponding Versions.xcconfig
# file. xcconfig is the single source of truth; pbxproj is fully regenerated
# by xcodegen and therefore loses any UI edit on the next regen unless we
# reverse-sync first.
#
# Why this script exists:
# - .xcodeproj/ is gitignored and regenerated by `xcodegen generate`.
# - project.yml / project-mac.yml / project-ios.yml all use `configFiles:`
#   to point at a Versions.xcconfig — so xcconfig values are the persistent
#   on-disk source of truth.
# - Xcode UI edits land in pbxproj target overrides. This script lifts those
#   overrides back into xcconfig, then `regen-all.sh` regenerates pbxproj —
#   the freshly-generated pbxproj only references xcconfig and target
#   overrides are gone, so UI edits round-trip cleanly through xcodegen.
#
# Workflow (you don't normally call this directly):
#   1. Edit Version / Build in Xcode UI.
#   2. Run `bash scripts/regen-all.sh` (calls this script, then xcodegen).
#   3. Commit Versions.xcconfig (and any sibling iOS Versions.xcconfig).
#
# Mappings:
#   PUBLIC  Termura.xcodeproj                        → <pub>/Versions.xcconfig
#   PRIVATE <sibling>/Termura-Mac.xcodeproj          → <pub>/Versions.xcconfig (shared)
#   PRIVATE <sibling>/iOS/TermuraRemote.xcodeproj    → <sibling>/iOS/Versions.xcconfig
#
# Mac and Mac-paid always ship the same version, so they share one xcconfig.
# iOS is a separate product and has its own.
#
# Sibling private repo path is supplied via the env var TERMURA_HARNESS_ROOT
# by the caller (regen-all.sh / quality-gate.sh / pre-commit). Keeping the
# string out of this script preserves the open-core leak baseline (CLAUDE.md
# §12.3) — only the four whitelisted orchestrator scripts may name the
# private repo path literally.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

PUBLIC_XCCONFIG="$REPO_ROOT/Versions.xcconfig"
PUBLIC_MAC_PBX="$REPO_ROOT/Termura.xcodeproj/project.pbxproj"

# Optional sibling. Empty → Free / open-core build, only public Mac is checked.
SIBLING="${TERMURA_HARNESS_ROOT:-}"
PRIVATE_MAC_PBX=""
PRIVATE_IOS_PBX=""
IOS_XCCONFIG=""
if [ -n "$SIBLING" ] && [ -d "$SIBLING" ]; then
    PRIVATE_MAC_PBX="$SIBLING/Termura-Mac.xcodeproj/project.pbxproj"
    PRIVATE_IOS_PBX="$SIBLING/iOS/TermuraRemote.xcodeproj/project.pbxproj"
    IOS_XCCONFIG="$SIBLING/iOS/Versions.xcconfig"
fi

# Extracts every unique non-empty value of `KEY = …;` from the given pbxproj,
# stripping surrounding quotes. Empty if the pbxproj is missing or has no
# matching line (the pbxproj was regenerated and now only references the
# xcconfig — i.e. there is no override to lift).
extract_unique() {
    local pbx="$1" key="$2"
    [ -f "$pbx" ] || return 0
    grep -oE "${key} = [^;]+;" "$pbx" 2>/dev/null \
        | sed -E "s/${key} = (.+);/\\1/" \
        | sed -E 's/^"(.*)"$/\1/' \
        | sort -u
}

# Reads MARKETING_VERSION / CURRENT_PROJECT_VERSION currently in an xcconfig.
# Tolerates absent file (returns empty).
read_xcconfig() {
    local file="$1" key="$2"
    [ -f "$file" ] || return 0
    grep -E "^[[:space:]]*${key}[[:space:]]*=" "$file" \
        | head -1 \
        | sed -E "s/^[[:space:]]*${key}[[:space:]]*=[[:space:]]*//" \
        | sed -E 's/[[:space:]]*$//'
}

# Writes `KEY = VALUE` into an xcconfig file in-place. Replaces an existing
# line with the same key; if the key is missing, appends it.
write_xcconfig() {
    local file="$1" key="$2" value="$3"
    if [ ! -f "$file" ]; then
        echo "ERROR: xcconfig $file does not exist; create it first." >&2
        exit 1
    fi
    if grep -qE "^[[:space:]]*${key}[[:space:]]*=" "$file"; then
        # BSD sed (macOS) requires an explicit empty backup suffix.
        sed -i '' -E "s|^([[:space:]]*${key}[[:space:]]*=).*|\\1 ${value}|" "$file"
    else
        printf '%s = %s\n' "$key" "$value" >> "$file"
    fi
}

# Merges values lifted from one or more pbxprojs into a single xcconfig.
# - PBXES is a `:`-separated list of pbxproj paths (any may be absent or empty).
#
# Why we filter out values that already equal the current xcconfig:
#   xcodegen 2.x emits MARKETING_VERSION/CURRENT_PROJECT_VERSION on EVERY
#   target's buildSettings — application + Tests + UITests — copied from
#   the project-level base. When the user edits the app's Version in the
#   Xcode UI, only the application target's override changes; the Tests
#   targets keep echoing the old value. Treating those echoes as a
#   conflict would block every UI edit until the user manually pokes the
#   Tests targets. Instead: drop values that equal what the xcconfig
#   already holds; whatever remains IS the UI edit.
#
# Conflict rules after filtering:
#   - 0 distinct candidates  → no UI edit pending; leave xcconfig alone.
#   - 1 distinct candidate   → that's the UI edit; write it.
#   - 2+ distinct candidates → user typed two different versions across
#     the public/private Mac UIs, or across distinct configurations.
#     Hard fail — pick one and re-edit.
#
# Returns 0 on success (xcconfig possibly updated) or 1 on conflict.
sync_one() {
    local label="$1" pbxes="$2" xcconfig="$3"

    local xc_mv xc_pv
    xc_mv="$(read_xcconfig "$xcconfig" MARKETING_VERSION)"
    xc_pv="$(read_xcconfig "$xcconfig" CURRENT_PROJECT_VERSION)"

    if [ -z "$xc_mv" ] || [ -z "$xc_pv" ]; then
        echo "ERROR [${label}]: ${xcconfig} is missing MARKETING_VERSION or CURRENT_PROJECT_VERSION." >&2
        return 1
    fi

    local mv_all=""
    local pv_all=""
    local IFS_BAK="$IFS"
    IFS=':'
    # shellcheck disable=SC2086
    for pbx in $pbxes; do
        [ -n "$pbx" ] || continue
        local mv pv
        mv="$(extract_unique "$pbx" MARKETING_VERSION)"
        pv="$(extract_unique "$pbx" CURRENT_PROJECT_VERSION)"
        [ -n "$mv" ] && mv_all="${mv_all}${mv}"$'\n'
        [ -n "$pv" ] && pv_all="${pv_all}${pv}"$'\n'
    done
    IFS="$IFS_BAK"

    # Distinct candidate set = pbxproj values minus echoes that already
    # match the xcconfig (those came from xcodegen's last regen, not
    # from a UI edit).
    local mv_cand pv_cand
    mv_cand="$(printf '%s' "$mv_all" | grep -v '^$' | sort -u | grep -vxF "$xc_mv" || true)"
    pv_cand="$(printf '%s' "$pv_all" | grep -v '^$' | sort -u | grep -vxF "$xc_pv" || true)"

    if [ -z "$mv_cand" ] && [ -z "$pv_cand" ]; then
        echo "OK [${label}]: no UI override pending (MARKETING_VERSION=${xc_mv}, CURRENT_PROJECT_VERSION=${xc_pv})."
        return 0
    fi

    if [ -n "$mv_cand" ] && [ "$(printf '%s\n' "$mv_cand" | wc -l | tr -d ' ')" -ne 1 ]; then
        echo "ERROR [${label}]: conflicting MARKETING_VERSION across pbxprojs:" >&2
        printf '  %s\n' "$mv_cand" >&2
        echo "  Open Xcode and set the same value across all UIs." >&2
        return 1
    fi
    if [ -n "$pv_cand" ] && [ "$(printf '%s\n' "$pv_cand" | wc -l | tr -d ' ')" -ne 1 ]; then
        echo "ERROR [${label}]: conflicting CURRENT_PROJECT_VERSION across pbxprojs:" >&2
        printf '  %s\n' "$pv_cand" >&2
        return 1
    fi

    local mv_new="${mv_cand:-$xc_mv}"
    local pv_new="${pv_cand:-$xc_pv}"

    write_xcconfig "$xcconfig" MARKETING_VERSION "$mv_new"
    write_xcconfig "$xcconfig" CURRENT_PROJECT_VERSION "$pv_new"
    echo "UPDATED [${label}]: ${xcconfig#"$REPO_ROOT/"}"
    [ "$xc_mv" != "$mv_new" ] && echo "  MARKETING_VERSION:        ${xc_mv} → ${mv_new}"
    [ "$xc_pv" != "$pv_new" ] && echo "  CURRENT_PROJECT_VERSION:  ${xc_pv} → ${pv_new}"
    return 0
}

fail=0

sync_one "Mac" "${PUBLIC_MAC_PBX}:${PRIVATE_MAC_PBX}" "$PUBLIC_XCCONFIG" || fail=1

if [ -n "$IOS_XCCONFIG" ]; then
    sync_one "iOS" "$PRIVATE_IOS_PBX" "$IOS_XCCONFIG" || fail=1
else
    echo "skip [iOS]: no sibling repo provided (TERMURA_HARNESS_ROOT unset, Free build)."
fi

exit "$fail"
